### ISSUE TITLE
Definitieve indeling laat lege lijst zien

### ISSUE THREAD

**Issue by nootr** [PJvanDiepen/COOLbackend#30]
Dag Peter!

Als de indeling nog niet definitief is, kan ik deze inzien, maar wanneer deze om 19:00 definitief wordt is de lijst niet meer te zien en zie ik in de console de volgende error:

```
ronde.js:132 Uncaught (in promise) ReferenceError: gebruiker is not defined
    at uitslagWijzigen (ronde.js:132:39)
    at resultaatSelecteren (ronde.js:115:9)
    at uitslagenRonde (ronde.js:79:36)
    at async ronde.js:50:5
```

<img width="605" alt="Screenshot 2023-09-19 at 19 25 15" src="https://github.com/PJvanDiepen/COOLbackend/assets/16090423/7db95774-fd99-4fc6-a4c5-e7a6248c96e0">

Als ik kijk naar `ronde.js:132` zoals deze ingeladen is in mijn browser, zie ik:

```js
function uitslagWijzigen(uitslag)  {
    if (zyq.o_o_o.seizoen !== zyq.ditSeizoen) { // vorig seizoen nooit wijzigen
        return false;
    } else if (zyq.gebruiker.mutatieRechten >= db.WEDSTRIJDLEIDER) {
        return true;
    } else if (zyq.gebruiker.mutatieRechten >= db.GEREGISTREERD && uitslag.resultaat === "") { // indien nog geen resultaat
        return uitslag.knsbNummer === gebruiker.knsbNummer || uitslag.tegenstanderNummer === gebruiker.knsbNummer;
    } else {
        return false;
    }
}
```

Daar waar `zyq.gebruiker` staat gaat alles goed, maar `gebruiker` zonder `zyq` is dus undefined. Ik verwacht dus dat dit de fix is:

```diff
function uitslagWijzigen(uitslag)  {
    if (zyq.o_o_o.seizoen !== zyq.ditSeizoen) { // vorig seizoen nooit wijzigen
        return false;
    } else if (zyq.gebruiker.mutatieRechten >= db.WEDSTRIJDLEIDER) {
        return true;
    } else if (zyq.gebruiker.mutatieRechten >= db.GEREGISTREERD && uitslag.resultaat === "") { // indien nog geen resultaat
-        return uitslag.knsbNummer === gebruiker.knsbNummer || uitslag.tegenstanderNummer === gebruiker.knsbNummer;
+        return uitslag.knsbNummer === zyq.gebruiker.knsbNummer || uitslag.tegenstanderNummer === zyq.gebruiker.knsbNummer;
    } else {
        return false;
    }
}
```

**Comment by nootr** [comment]
Ik heb dit probleem overigens niet op mijn mobiel, waar ik met dezelfde "token" ben ingelogd.

Edit: die zal misschien verouderde js files uit een cache gebruiken.

**Comment by nootr** [comment]
Ik zat te kijken of ik een Pull Request kon maken, maar klopt het dat deze Github repository niet gelijk loopt aan wat er nu live staat?
